language: cpp

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: false
          compiler: gcc
          addons:
            apt:
              packages:
                - qt5-default
                - qtbase5-dev-tools
                - qt5-qmake
                - libtag1-dev
        - os: osx
          osx_image: xcode8.2
          compiler: clang

before_install:
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        brew update;
      fi

install:
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        brew update;
        brew install qt5;
        brew link --force qt5;
        brew install taglib;
      fi

before_script:

script:
    - cd src && qmake UltraStar-Creator.pro && make
    - cd ../bin/release
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        if [ -r "UltraStar-Creator.app" ]; then
            macdeployqt UltraStar-Creator.app -dmg;
            link=$(curl --upload-file 'UltraStar-Creator.dmg' "https://transfer.sh/UltraStar-Creator-$(git rev-parse --short HEAD).dmg");
            echo "UltraStar-Creator.dmg should be available at:";
            echo "    $link";
        fi
      fi

notifications:
    email: false
